version: '2.4'

services:
  martian:
    build:
      context: ./service
    volumes:
      - ./service/users:/users
    ports:
      - 9999:1337
    restart: on-failure
    pids_limit: 256
    mem_limit: 500M
    cpus: 0.5