[package]
name = "backend_internal"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "1.0"
serde = { version = "1.0.105", features = ["derive"] }
reqwest = { version = "0.10", features = ["json", "blocking"] }
postgres = "0.17"
serde_json = "1.0"