version: '2.4'

services:
  core:
    build: core
    ports:
      - "3333:3333"
    restart: always
    depends_on:
      - db
      - messenger
    mem_limit: 300M
    cpus: 0.25

  db:
    image: mongo
    restart: always
    volumes:
    - "./data:/data/db"
    mem_limit: 500M
    cpus: 0.25

  messenger:
    build: message_service
    restart: always
    mem_limit: 300M
    cpus: 0.25

