version: '2.4'

services:
  core:
    build: core
    ports:
      - "3333:3333"
    restart: on-failure
    depends_on:
      - db
      - messenger
    mem_limit: 300M
    cpus: 0.25

  envoy:
    build: envoy
    ports:
    - "3334:8080"
    restart: on-failure
    depends_on:
      - core

  db:
    image: mongo
    restart: on-failure
    volumes:
    - "./data/db:/data/db"
    mem_limit: 500M
    cpus: 0.25

  nginx:
    image: nginx:1.15.11-alpine
    ports:
      - 3335:80
    restart: on-failure
    cpus: 0.20
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./front/build:/dist
    depends_on:
      - envoy


  messenger:
    build: message_service
    volumes:
        - "./data/messages:/tmp/messages"
    restart: always
    mem_limit: 300M
    cpus: 0.25


