version: '3'

services:
  core:
    build: core
    ports:
      - "3333:3333"
    restart: always
    depends_on:
      - db
      - messenger

  db:
    image: mongo
    restart: always
    volumes:
    - "./data:/data/db"

  messenger:
    build: message_service
    restart: always

